# Generated by Django 3.2.14 on 2022-10-14 08:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('project_core', '0178_auto_20220708_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the entry was created')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Date and time at which the entry was modified', null=True)),
                ('name', models.CharField(help_text='Name of the trace', max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraceCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=14)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=14)),
                ('trace', models.ForeignKey(help_text='Trace that the coordinate belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='trace_coordinates', to='project_core.trace')),
            ],
        ),
    ]
